version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017
environment:
  PFX_PASSWORD:
    secure: TOUK93S0KJBaB7vjTJ/Wxcy3bTw55VNfk05kiz37cyLbGlgrL2F6vYt9b+9ofz2j
  DIVVUN_KEY:
    secure: ackb0siNZbJLyOe1YR/lkfr0d4T98RpWjh45wdk/Nn0IEkAh0SgmnfnxEBDKZZwcwH0hNo8SvHOpV+WEc4GWglcq7CXLUTbiwP9cYD9phL6547vzTeZ17HCVQiq0QtO1
  DEPLOY_VERSION_VOIKKO: 5.0.1
  DEPLOY_VERSION_SPELLER_SE: 1.0.1
  DEPLOY_VERSION_SPELLER_SMA: 1.0.1
  DEPLOY_VERSION_SPELLER_SMJ: 1.0.1
  DEPLOY_VERSION_SPELLER_SMN: 1.0.1
  DEPLOY_VERSION_SPELLER_SMS: 1.0.1
  PAHKAT_REPO_NAME: windows-staging
  DEPLOY_SVN_URL: https://pahkat.uit.no/repo/windows-staging
  DEPLOY_SVN_USER: divvunci
  DEPLOY_SVN_PASSWORD:
    secure: +kBSsT/UuXPXDadjRA5hl3dIynEVqmdkvG0THk0Wk6Pfa2PBfbRzNOrtvx7HdVH3bWcueAl8WWiLwP6JapNYwKqBh3Dlye721AZ8GriB+UPfdP/5qSGy7Xg+W3ccMaX8
install:
- cmd: >-
    choco install svn

    choco install innosetup

    appveyor DownloadFile https://github.com/divvun/pahkat/releases/download/0.6.0/pahkat.exe

    move pahkat.exe C:\Windows\system32
build_script:
- ps: >-
    cd $Env:APPVEYOR_BUILD_FOLDER\win

    .\build.ps1
test: off
deploy_script:
- ps: >-
    $Env:BRANCH=$Env:APPVEYOR_REPO_BRANCH

    cd $Env:APPVEYOR_BUILD_FOLDER\win

    .\deploy.ps1